"""Verify the code-defined EEP engine against the official EnOcean certification vectors.

Fixtures (`tests/fixtures/certification/eep_certification.json`) are generated by
the official `*_test.xml` vectors (checked in; the extraction generator was retired in 0.9.2).
Each assertable entry (a field with a
machine-resolvable shortcut) is decoded and compared to the certified value.

Match rule (documented accommodations of the official vectors):
- enum/bool/string: exact, or the raw value matches;
- linear value: within one physical resolution step;
- a subset of vectors express a fractional physical value as an integer with the decimal dropped
  (e.g. `51` for `5.1 V`, `412` for `41.2 °C`) — accepted as value×10 / value×100 within one step.

Known residuals (~5%) are official-vector data quirks (bogus mid-point values, ½-step "ideal" meter
readings) and composite multi-byte fields (e.g. A5-13-06 GPS lat/long split MSB/LSB) that the engine
does not recombine. None are used by the deployed fleet. The test guards a regression floor.
"""

import json
import os

import pytest

import enoceanmqtt.eep_engine.utils as u
from enoceanmqtt.eep_engine.engine import decode, find_profile, select_case

FIX = os.path.join(
    os.path.dirname(__file__), "fixtures", "certification", "eep_certification.json"
)
CASES = json.load(open(FIX, encoding="utf-8"))["cases"]
META = {"LRN", "LRNB", "RORG", "FUNC", "TYPE", "STATUS", "Status"}

# Regression floor: the fraction of assertable certified values the engine reproduces. Currently
# ~0.95; the remainder are documented official-vector quirks + uncombined composite fields.
MIN_PASS_RATE = 0.95


def _field(case, shortcut):
    for f in case.fields + case.status_fields:
        if f.shortcut == shortcut:
            return f
    return None


def _step(field):
    if (
        field.kind == "value"
        and None not in (field.scale_min, field.scale_max, field.range_min, field.range_max)
        and field.range_max != field.range_min
    ):
        return abs(field.scale_max - field.scale_min) / abs(field.range_max - field.range_min)
    return None


def _matches(field, got, raw, exp):
    if isinstance(exp, (int, float)) and isinstance(got, (int, float)):
        step = _step(field)
        tol = (step * 1.01 + 1e-6) if step else 0.01
        if abs(got - exp) <= tol or raw == exp:
            return True
        # official "decimal dropped" convention (value expressed ×10 / ×100)
        return bool(step) and (abs(got - exp / 10.0) <= tol or abs(got - exp / 100.0) <= tol)
    return str(got) == str(exp) or raw == exp


def _iter_assertions():
    for c in CASES:
        prof = find_profile(c["rorg"], c["func"], c["type"])
        if prof is None:
            continue
        bit_data = u.to_bitarray(c["data"], 8 * len(c["data"]))
        bit_status = u.to_bitarray([c["status"] or 0], 8)
        case = select_case(prof, bit_data, bit_status)
        if case is None:
            continue
        dec = decode(case, bit_data, bit_status)
        for shortcut, exp in c["expect"].items():
            field = _field(case, shortcut)
            if shortcut in META or field is None:
                continue
            yield c, field, shortcut, exp, dec.get(shortcut)


def test_certification_pass_rate():
    total = passed = 0
    misses = []
    for c, field, shortcut, exp, decoded in _iter_assertions():
        total += 1
        if decoded is not None and _matches(field, decoded["value"], decoded["raw_value"], exp):
            passed += 1
        else:
            misses.append((c["eep"], c["test"], shortcut, exp, decoded and decoded["value"]))
    rate = passed / total if total else 0.0
    assert total > 900, f"expected the full certification corpus, got {total} assertions"
    assert rate >= MIN_PASS_RATE, (
        f"certification pass rate {rate:.3f} < {MIN_PASS_RATE} "
        f"({passed}/{total}); first misses: {misses[:15]}"
    )


@pytest.mark.parametrize(
    "data,shortcut,expected",
    [
        ([0x00, 0x00, 0xFF, 0x08], "TMP", 0.0),  # A5-02-05 min
        ([0x00, 0x00, 0x00, 0x08], "TMP", 40.0),  # A5-02-05 max
    ],
)
def test_a5_02_05_temperature_exact(data, shortcut, expected):
    """Concrete sanity: the temperature profile the fleet uses decodes to the certified values."""
    prof = find_profile(0xA5, 0x02, 0x05)
    bits = u.to_bitarray(data, 32)
    case = select_case(prof, bits, u.to_bitarray([0], 8))
    dec = decode(case, bits, u.to_bitarray([0], 8))
    assert round(dec[shortcut]["value"], 1) == expected


@pytest.mark.parametrize(
    "d0,expected_raw,expected_text",
    [
        (0x00, 0, "Moved from up to vertical"),
        (0x04, 0, "Moved from up to vertical"),
        (0x0C, 0, "Moved from up to vertical"),
        (0x08, 0, "Moved from up to vertical"),
        (0x10, 1, "Moved from vertical to up"),
        (0x14, 1, "Moved from vertical to up"),
        (0x1C, 1, "Moved from vertical to up"),
        (0x30, 3, "Moved from vertical to down"),
    ],
)
def test_f6_10_00_window_handle_decodes(d0, expected_raw, expected_text):
    """F6-10-00 (Window Handle) regression: WIN must decode the 2-bit field (bits 2-3) to
    0..3 with the official EEP.xml 2.6.4 descriptions and a 0..3 raw value.

    The pre-engine enocean library delivered exactly these (raw, description) pairs for the
    teach-in D0 bytes 0x04/0x0C and the operating bytes 0x10/0x14/0x1C/0x30, and the
    mapping.yaml templates depend on numeric WIN 0/1/3. A previous port of the engine
    declared WIN as (offset 0, size 8) with 8 value-less enum items, so every telegram
    decoded to the *whole byte* (0..255 raw, no enum match) and the HA templates broke.
    """
    prof = find_profile(0xF6, 0x10, 0x00)
    assert prof is not None, "F6-10-00 profile must exist"
    bits = u.to_bitarray([d0], 8)
    status = u.to_bitarray([0x20], 8)
    case = select_case(prof, bits, status)
    dec = decode(case, bits, status)
    win = dec["WIN"]
    assert win["raw_value"] == expected_raw, f"D0=0x{d0:02X} raw WIN"
    assert win["value"] == expected_text, f"D0=0x{d0:02X} enum WIN"
